### ISSUE TITLE
Unable to update screenshot

### ISSUE THREAD

**Issue by Fletchman1313** [blackholesuns/nmsce#24]
Posted a discovery here: https://nmsce.com/preview?i=27eb7977-b959-4d5a-a432-a8aeaf45b71f&g=Euclid&t=Ship

Realized that the glyphs weren't displaying, so I tried to change the screenshot.  It does not seem to update.

**Comment by CEbbinghaus** [comment]
Checking it seems to be showing the glyphs just fine. This might be because of our CDN caching the last version. Updating the image is going to take a bit since the servers have to pick up the change and distribute it globally, We could look into adding a note or seeing if we can invalidate the cache however for the moment it might just take a bit.

Can you confirm that this has been fixed on your end and if not can you try reloading the page using `Shift + F5` to make sure the image wasn't cached locally?

**Comment by Fletchman1313** [comment]
Hello,

Thanks for the reply.  I just checked and sure enough, the image has been
updated.  I guess it just took a while for it to show on my side (I had
cleared my cache earlier with Shift + F5 to no avail).

So, I was also going to open a minor issue about the "Galaxy" label not
showing up on the screenshot when picking that label.  I've been adding it
in as a text field instead.  Should I go ahead and open a separate issue or
do you just want to look at that real quick?
